# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cw2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    rb1text = ''
    rb2text = ''
    rb3text = ''

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 300)
        Dialog.setMinimumSize(QtCore.QSize(561, 300))
        Dialog.setMaximumSize(QtCore.QSize(561, 300))

        self.rb1_1 = QtWidgets.QRadioButton(Dialog)
        self.rb1_1.setGeometry(QtCore.QRect(60, 70, 96, 23))
        self.rb1_1.setObjectName("radioButton")
        self.rb1_2 = QtWidgets.QRadioButton(Dialog)
        self.rb1_2.setGeometry(QtCore.QRect(60, 100, 96, 23))
        self.rb1_2.setObjectName("radioButton_2")
        self.rb1_3 = QtWidgets.QRadioButton(Dialog)
        self.rb1_3.setGeometry(QtCore.QRect(60, 130, 96, 23))
        self.rb1_3.setObjectName("radioButton_3")

        self.rb1 = QtWidgets.QButtonGroup()
        self.rb1.addButton(self.rb1_1)
        self.rb1.addButton(self.rb1_2)
        self.rb1.addButton(self.rb1_3)

        self.rb1.buttonClicked.connect(self.add_color1)

        self.rb2_1 = QtWidgets.QRadioButton(Dialog)
        self.rb2_1.setGeometry(QtCore.QRect(230, 70, 96, 23))
        self.rb2_1.setObjectName("radioButton_5")
        self.rb2_2 = QtWidgets.QRadioButton(Dialog)
        self.rb2_2.setGeometry(QtCore.QRect(230, 100, 96, 23))
        self.rb2_2.setObjectName("radioButton_4")
        self.rb2_3 = QtWidgets.QRadioButton(Dialog)
        self.rb2_3.setGeometry(QtCore.QRect(230, 130, 96, 23))
        self.rb2_3.setObjectName("radioButton_6")

        self.rb2 = QtWidgets.QButtonGroup()
        self.rb2.addButton(self.rb2_1)
        self.rb2.addButton(self.rb2_2)
        self.rb2.addButton(self.rb2_3)

        self.rb2.buttonClicked.connect(self.add_color2)

        self.rb3_1 = QtWidgets.QRadioButton(Dialog)
        self.rb3_1.setGeometry(QtCore.QRect(410, 70, 96, 23))
        self.rb3_1.setObjectName("radioButton_8")
        self.rb3_2 = QtWidgets.QRadioButton(Dialog)
        self.rb3_2.setGeometry(QtCore.QRect(410, 100, 96, 23))
        self.rb3_2.setObjectName("radioButton_7")
        self.rb3_3 = QtWidgets.QRadioButton(Dialog)
        self.rb3_3.setGeometry(QtCore.QRect(410, 130, 96, 23))
        self.rb3_3.setObjectName("radioButton_9")
        self.rb3 = QtWidgets.QButtonGroup()
        self.rb3.addButton(self.rb3_1)
        self.rb3.addButton(self.rb3_2)
        self.rb3.addButton(self.rb3_3)

        self.rb3.buttonClicked.connect(self.add_color3)

        self.print_func = QtWidgets.QLabel(Dialog)
        self.print_func.setGeometry(QtCore.QRect(70, 240, 441, 17))
        self.print_func.setText("")
        self.print_func.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)

        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(400, 20, 121, 31))

        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(410, 190, 91, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.last_print)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def add_color1(self):
        if self.rb1_1.isChecked():
            self.rb1text = 'Красный'
        elif self.rb1_2.isChecked():
            self.rb1text = 'Зеленый'
        else:
            self.rb1text = 'Синий'

    def add_color2(self):
        if self.rb2_1.isChecked():
            self.rb2text = 'Красный'
        elif self.rb2_2.isChecked():
            self.rb2text = 'Зеленый'
        else:
            self.rb2text = 'Синий'

    def add_color3(self):
        if self.rb3_1.isChecked():
            self.rb3text = 'Красный'
        elif self.rb3_2.isChecked():
            self.rb3text = 'Зеленый'
        else:
            self.rb3text = 'Синий'

    def last_print(self):
        self.print_func.setText(f'Цвета: {self.rb1text}, {self.rb2text} и {self.rb3text}')

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Текстовый флаг"))
        self.rb1_1.setText(_translate("Dialog", "Красный"))
        self.rb1_2.setText(_translate("Dialog", "Зеленый"))
        self.rb1_3.setText(_translate("Dialog", "Синий"))
        self.rb2_1.setText(_translate("Dialog", "Красный"))
        self.rb2_2.setText(_translate("Dialog", "Зеленый"))
        self.rb2_3.setText(_translate("Dialog", "Синий"))
        self.rb3_1.setText(_translate("Dialog", "Красный"))
        self.rb3_2.setText(_translate("Dialog", "Зеленый"))
        self.rb3_3.setText(_translate("Dialog", "Синий"))
        self.label.setText(_translate("Dialog", "Цвет №1"))
        self.label_2.setText(_translate("Dialog", "Цвет №2"))
        self.label_3.setText(_translate("Dialog", "Цвет №3"))
        self.pushButton.setText(_translate("Dialog", "Сделать флаг"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Dialog()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
