# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(241, 376)
        self.btn1 = QtWidgets.QPushButton(Dialog)
        self.btn1.setGeometry(QtCore.QRect(10, 90, 41, 41))
        self.btn1.setObjectName("btn1")
        self.plus = QtWidgets.QPushButton(Dialog)
        self.plus.setGeometry(QtCore.QRect(190, 90, 41, 41))
        self.plus.setObjectName("plus")
        self.btn4 = QtWidgets.QPushButton(Dialog)
        self.btn4.setGeometry(QtCore.QRect(10, 150, 41, 41))
        self.btn4.setObjectName("btn4")
        self.btn6 = QtWidgets.QPushButton(Dialog)
        self.btn6.setGeometry(QtCore.QRect(130, 150, 41, 41))
        self.btn6.setObjectName("btn6")
        self.minus = QtWidgets.QPushButton(Dialog)
        self.minus.setGeometry(QtCore.QRect(190, 150, 41, 41))
        self.minus.setObjectName("minus")
        self.btn0 = QtWidgets.QPushButton(Dialog)
        self.btn0.setGeometry(QtCore.QRect(70, 270, 41, 41))
        self.btn0.setObjectName("btn0")
        self.fact = QtWidgets.QPushButton(Dialog)
        self.fact.setGeometry(QtCore.QRect(130, 330, 41, 41))
        self.fact.setObjectName("fact")
        self.btn2 = QtWidgets.QPushButton(Dialog)
        self.btn2.setGeometry(QtCore.QRect(70, 90, 41, 41))
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(Dialog)
        self.btn3.setGeometry(QtCore.QRect(130, 90, 41, 41))
        self.btn3.setObjectName("btn3")
        self.btn5 = QtWidgets.QPushButton(Dialog)
        self.btn5.setGeometry(QtCore.QRect(70, 150, 41, 41))
        self.btn5.setObjectName("btn5")
        self.btn7 = QtWidgets.QPushButton(Dialog)
        self.btn7.setGeometry(QtCore.QRect(10, 210, 41, 41))
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(Dialog)
        self.btn8.setGeometry(QtCore.QRect(70, 210, 41, 41))
        self.btn8.setObjectName("btn8")
        self.split = QtWidgets.QPushButton(Dialog)
        self.split.setGeometry(QtCore.QRect(190, 270, 41, 41))
        self.split.setObjectName("split")
        self.scrt = QtWidgets.QPushButton(Dialog)
        self.scrt.setGeometry(QtCore.QRect(10, 330, 41, 41))
        self.scrt.setObjectName("scrt")
        self.flt = QtWidgets.QPushButton(Dialog)
        self.flt.setGeometry(QtCore.QRect(10, 270, 41, 41))
        self.flt.setObjectName("flt")
        self.elevate = QtWidgets.QPushButton(Dialog)
        self.elevate.setGeometry(QtCore.QRect(70, 330, 41, 41))
        self.elevate.setObjectName("elevate")
        self.clear = QtWidgets.QPushButton(Dialog)
        self.clear.setGeometry(QtCore.QRect(190, 330, 41, 41))
        self.clear.setObjectName("clear")
        self.calc = QtWidgets.QPushButton(Dialog)
        self.calc.setGeometry(QtCore.QRect(130, 270, 41, 41))
        self.calc.setObjectName("calc")
        self.multyplue = QtWidgets.QPushButton(Dialog)
        self.multyplue.setGeometry(QtCore.QRect(190, 210, 41, 41))
        self.multyplue.setObjectName("multyplue")
        self.btn9 = QtWidgets.QPushButton(Dialog)
        self.btn9.setGeometry(QtCore.QRect(130, 210, 41, 41))
        self.btn9.setObjectName("btn9")
        self.res = QtWidgets.QLCDNumber(Dialog)
        self.res.setGeometry(QtCore.QRect(0, 10, 241, 71))
        self.res.setObjectName("res")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn1.setText(_translate("Dialog", "1"))
        self.plus.setText(_translate("Dialog", "+"))
        self.btn4.setText(_translate("Dialog", "4"))
        self.btn6.setText(_translate("Dialog", "6"))
        self.minus.setText(_translate("Dialog", "-"))
        self.btn0.setText(_translate("Dialog", "0"))
        self.fact.setText(_translate("Dialog", "!"))
        self.btn2.setText(_translate("Dialog", "2"))
        self.btn3.setText(_translate("Dialog", "3"))
        self.btn5.setText(_translate("Dialog", "5"))
        self.btn7.setText(_translate("Dialog", "7"))
        self.btn8.setText(_translate("Dialog", "8"))
        self.split.setText(_translate("Dialog", "/"))
        self.scrt.setText(_translate("Dialog", "√"))
        self.flt.setText(_translate("Dialog", "."))
        self.elevate.setText(_translate("Dialog", "^"))
        self.clear.setText(_translate("Dialog", "C"))
        self.calc.setText(_translate("Dialog", "="))
        self.multyplue.setText(_translate("Dialog", "*"))
        self.btn9.setText(_translate("Dialog", "9"))



if __name__ == "__main__":
  app = QtWidgets.QApplication(sys.argv)
  Form = QtWidgets.QWidget()
  ui = Ui_Dialog()
  ui.setupUi(Form)
  Form.show()
  sys.exit(app.exec_())